# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_auto_20170927_1900'),
        ('rewards', '0004_auto_20170927_1724'),
    ]

    operations = [
    ]
