# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_auto_20170928_2322'),
        ('rewards', '0005_merge_20170928_1847'),
    ]

    operations = [
    ]
