# Generated by Django 2.0.8 on 2018-11-13 20:53

from django.db import migrations


def reset_true_grit_to_one(apps, schema_editor):
    User = apps.get_model('oddslingers', 'User')
    Badge = apps.get_model('rewards', 'Badge')

    for user in User.objects.all():
        true_grit_badges = user.badge_set.filter(name='true_grit').order_by('created')
        if true_grit_badges.exists():
            first_true_grit_ever = true_grit_badges.first()
            Badge.objects.filter(user=user, name='true_grit')\
                         .exclude(id=first_true_grit_ever.id)\
                         .delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0013_auto_20181016_2105'),
    ]

    operations = [
        migrations.RunPython(reset_true_grit_to_one)
    ]
