# Generated by Django 2.0.8 on 2019-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0019_auto_20190103_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='season',
            field=models.IntegerField(),
        ),
    ]
