# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0002_socket_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='user_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
