# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0003_auto_20170609_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='path',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
