# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0005_socket_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
