# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0006_auto_20170630_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
