# Generated by Django 2.0.7 on 2018-07-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sockets', '0007_socket_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
