# Steps to set up a new docker-compose machine:
#
# docker-compose run django ./manage.py migrate
# docker-compose run django ./manage.py createsuperuser
# docker-compose up


version: '3'

volumes:
  node_modules:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    links: 
      - "django"

  postgres:
    image: postgres:13
    env_file:
      - ./env/prod-docker.env
      - ./.secrets-prod.env
    ports:
      - 5432:5432
    expose:
      - 5432
    command: postgres -c shared_buffers=1GB

  redis:
    image: redis:5-alpine
    entrypoint: redis-server --appendonly yes
    expose:
      - 6379

  django:
    build: .
    image: oddslingers:django_base
    hostname: oddslingers-prod
    working_dir: /opt/oddslingers.poker/core/
    command: daphne -b 0.0.0.0 -p 8000 oddslingers.asgi:channel_layer
    stdin_open: true
    tty: true
    depends_on: 
      - postgres
      - redis
    environment:
      ODDSLINGERS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: "oddslingers.settings"
      IS_DOCKER: 1
    ports:
      - 8000:8000
    env_file:
      - ./env/prod-docker.env
      - ./.secrets-prod.env
    expose: 
      - 8000

  worker:
    image: oddslingers:django_base
    working_dir: /opt/oddslingers.poker/core/
    entrypoint: /opt/oddslingers.poker/bin/worker-docker-entrypoint.sh
    user: root
    depends_on:
      - postgres
      - redis
    environment:
      ODDSLINGERS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: "oddslingers.settings"
      IS_DOCKER: 1
    env_file:
      - ./env/prod-docker.env
      - ./.secrets-prod.env

  botbeat:
    image: oddslingers:django_base
    working_dir: /opt/oddslingers.poker/core/
    command: ./manage.py bot_heartbeat
    depends_on:
      - postgres
      - redis
    environment:
      ODDSLINGERS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: "oddslingers.settings"
      IS_DOCKER: 1
    restart: on-failure
    env_file:
      - ./env/prod-docker.env
      - ./.secrets-prod.env

  dramatiq:
    image: oddslingers:django_base
    working_dir: /opt/oddslingers.poker/core/
    command: nice -15 ./manage.py rundramatiq --processes 1 --threads 1
    environment:
      ODDSLINGERS_ENV: PROD
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    cap_add:
      - SYS_NICE
    depends_on: 
      - redis
      - postgres
    env_file:
      - ./env/prod-docker.env
      - ./.secrets-prod.env
