apiVersion: v1
data:
  CLOUDFLARE_EMAIL: set-this-value-in-secrets.env
  CLOUDFLARE_KEY: set-this-value-in-secrets.env
  CLOUDFLARE_ZONE_ID: set-this-value-in-secrets.env
  MAILGUN_API_KEY: set-this-value-in-secrets.env
  POSTGRES_PASSWORD: set-this-value-in-secrets.env
  SECRET_KEY: set-this-value-in-secrets.env
  SENTRY_DSN_KEY: set-this-value-in-secrets.env
  SENTRY_DSN_SECRET: set-this-value-in-secrets.env
  SENTRY_PROJECT_ID: set-this-value-in-secrets.env
  ZULIP_API_KEY: set-this-value-in-secrets.env
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: django-secrets-prod-env
  name: secrets-prod-env
