# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0020_merge_20180129_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('odds', models.DecimalField(decimal_places=10, max_digits=15)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('starting_stack', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rebuys', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.PokerTable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
