# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebet',
            name='paid',
        ),
        migrations.AddField(
            model_name='sidebet',
            name='ending_stack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='sidebet',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed')], default='active', max_length=25),
        ),
    ]
