# Generated by Django 2.0.7 on 2018-08-14 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidebets', '0005_sidebet_sidebet_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poker.Player'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='sidebet_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sidebets.Sidebet'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poker.PokerTable'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
