# Generated by Django 2.0.8 on 2018-09-11 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidebets', '0006_auto_20180814_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.Player'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='sidebet_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sidebets.Sidebet'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.PokerTable'),
        ),
        migrations.AlterField(
            model_name='sidebet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
