# Generated by Django 2.0.8 on 2018-10-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0036_auto_20180928_2044'),
        ('sidebets', '0007_auto_20180911_1841'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='sidebet',
            index_together={('table', 'status')},
        ),
    ]
