# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('source_id', models.UUIDField()),
                ('dest_id', models.UUIDField()),
                ('amt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dest_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recv_transfers', to='contenttypes.ContentType')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transfers', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.UUIDField(default='10101010101010101010101010101010', editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
