# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransfer',
            name='dest_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='balancetransfer',
            name='source_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
