# Generated by Django 2.0.7 on 2018-07-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0002_auto_20170302_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransfer',
            name='dest_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'oddslingers'), ('model', 'User')), models.Q(('app_label', 'poker'), ('model', 'PokerTable')), models.Q(('app_label', 'banker'), ('model', 'Cashier')), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='recv_transfers', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='balancetransfer',
            name='source_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'oddslingers'), ('model', 'User')), models.Q(('app_label', 'poker'), ('model', 'PokerTable')), models.Q(('app_label', 'banker'), ('model', 'Cashier')), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_transfers', to='contenttypes.ContentType'),
        ),
    ]
