# Generated by Django 2.0.8 on 2018-09-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker', '0003_auto_20180723_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransfer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
