# Generated by Django 2.0.8 on 2018-09-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('banker', '0004_auto_20180926_0612'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='balancetransfer',
            index_together={('source_type', 'dest_type', 'timestamp')},
        ),
    ]
