# Generated by Django 2.0.7 on 2018-07-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0025_auto_20180724_1947'),
        ('support', '0002_auto_20180725_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.PokerTable'),
        ),
    ]
