# Generated by Django 2.0.7 on 2018-07-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_supportticket_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='source',
            field=models.IntegerField(choices=[(0, 'Admin Created'), (1, 'Email to support@oddslingers.com'), (2, 'Support Page Submition'), (3, 'Report Bug on a Table'), (4, 'Tablebeat Exception'), (5, 'Botbeat Exception')], default=0),
        ),
    ]
