# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedlink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
