# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linky', '0002_auto_20180614_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedlink',
            name='target_url',
            field=models.URLField(max_length=128),
        ),
    ]
