# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20170214_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='seconds_per_action_base',
            field=models.IntegerField(default=15),
        ),
    ]
