# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0007_auto_20170520_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='name',
            field=models.CharField(default='Homepage Table', max_length=128, unique=True),
        ),
    ]
