# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_auto_20170630_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='name',
            field=models.CharField(db_index=True, default='Homepage Table', max_length=128, unique=True),
        ),
    ]
