# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0015_auto_20170927_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handhistoryevent',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
