# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0016_auto_20170928_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='leaving_table',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sit_in_at_blinds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sitting_out',
        ),
        migrations.AddField(
            model_name='player',
            name='playing_state_int',
            field=models.IntegerField(choices=[(1, 'SITTING_IN'), (2, 'SITTING_OUT'), (3, 'SIT_IN_PENDING'), (4, 'SIT_OUT_PENDING'), (5, 'SIT_IN_AT_BLINDS_PENDING'), (6, 'LEAVE_SEAT_PENDING'), (7, 'DISCONNECTED')], null=True),
        ),
        migrations.AlterField(
            model_name='chatline',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
