# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0016_auto_20170928_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerTableStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('players_per_flop_pct', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('avg_pot', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('avg_stack', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('hands_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('num_samples', models.IntegerField(default=0)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poker.PokerTable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
