# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0017_auto_20171024_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='n_hands_played',
            field=models.IntegerField(default=0),
        ),
    ]
