# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0018_player_n_hands_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
