# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0017_pokertablestats'),
        ('poker', '0019_pokertable_created_by'),
    ]

    operations = [
    ]
