# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0023_auto_20180411_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='sidebets_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
