# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_tournament_admin(apps, schema_editor):
    PokerTournament = apps.get_model('poker', 'PokerTournament')
    for tournament in PokerTournament.objects.all():
        tournament.tournament_admin = tournament.entrants.first()
        tournament.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0023_auto_20180614_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertournament',
            name='tournament_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_tournament_admin),
    ]
