# Generated by Django 2.0.7 on 2018-07-24 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0024_pokertournament_party_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='chat_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.ChatHistory'),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.Freezeout'),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='chat_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poker.ChatHistory'),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pokertournament',
            name='tournament_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
