# Generated by Django 2.0.8 on 2018-08-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0025_auto_20180724_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertablestats',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='poker.PokerTable'),
        ),
    ]
