# Generated by Django 2.0.7 on 2018-08-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0025_auto_20180724_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
