# Generated by Django 2.0.7 on 2018-08-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0026_pokertable_is_tutorial'),
        ('poker', '0026_auto_20180807_0128'),
    ]

    operations = [
    ]
