# Generated by Django 2.0.7 on 2018-08-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0025_merge_20180724_2137'),
        ('poker', '0027_merge_20180807_1635'),
    ]

    operations = [
    ]
