# Generated by Django 2.0.8 on 2018-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0027_merge_20180807_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
