# Generated by Django 2.0.8 on 2018-09-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0028_pokertable_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='name',
            field=models.CharField(db_index=True, default='Homepage Table', max_length=128),
        ),
    ]
