# Generated by Django 2.0.8 on 2018-09-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0028_auto_20180903_0114'),
        ('poker', '0029_auto_20180903_0246'),
    ]

    operations = [
    ]
