# Generated by Django 2.0.8 on 2018-09-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0030_merge_20180904_1453'),
        ('poker', '0030_merge_20180904_0807'),
    ]

    operations = [
    ]
