# Generated by Django 2.0.8 on 2018-09-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0029_auto_20180814_1725'),
        ('poker', '0030_merge_20180904_1453'),
    ]

    operations = [
    ]
