# Generated by Django 2.0.8 on 2018-09-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0031_merge_20180906_2133'),
        ('poker', '0031_merge_20180906_1954'),
    ]

    operations = [
    ]
