# Generated by Django 2.0.8 on 2018-09-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0032_auto_20180910_1422'),
        ('poker', '0032_auto_20180907_2152'),
    ]

    operations = [
    ]
