# Generated by Django 2.0.8 on 2018-09-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0033_merge_20180921_0624'),
        ('poker', '0033_auto_20180908_1801'),
    ]

    operations = [
    ]
