# Generated by Django 2.0.8 on 2018-09-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0034_merge_20180925_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
