# Generated by Django 2.0.8 on 2018-09-28 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0035_auto_20180926_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatline',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='chatline',
            unique_together={('chat_history', 'timestamp', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='chatline',
            index_together={('chat_history', 'timestamp')},
        ),
    ]
