# Generated by Django 2.0.8 on 2018-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0036_auto_20180928_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokertournament',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
