# Generated by Django 2.0.8 on 2018-10-26 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0037_auto_20181010_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_action_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
