# Generated by Django 2.2.11 on 2020-12-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0039_pokertable_last_human_action_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertournament',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'STARTED'), (3, 'FINISHED'), (4, 'CANCELED')], default=1),
        ),
    ]
