# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_buyin',
            field=models.IntegerField(default=100),
        ),
    ]
