# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0002_user_default_buyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_buyin',
            field=models.IntegerField(default=200),
        ),
    ]
