# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0005_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='login_time',
            new_name='login_date',
        ),
    ]
