# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0007_auto_20170802_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, null=True, max_length=255),
        ),
    ]
