# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0010_auto_20170923_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
