# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0011_auto_20170923_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muted_sounds',
            field=models.BooleanField(default=False),
        ),
    ]
