# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0012_user_muted_sounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
