# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0013_auto_20180302_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
