# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0015_auto_20180404_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_spectator_msgs',
            field=models.BooleanField(default=True),
        ),
    ]
