# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0016_user_show_spectator_msgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sit_behaviour',
        ),
        migrations.AddField(
            model_name='user',
            name='sit_behaviour_int',
            field=models.IntegerField(choices=[(2, 'SITTING_OUT'), (5, 'SIT_IN_AT_BLINDS_PENDING'), (3, 'SIT_IN_PENDING')], default=5),
        ),
    ]
