# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0017_auto_20180723_0336'),
        ('oddslingers', '0017_user_played_first_tournament'),
    ]

    operations = [
    ]
