# Generated by Django 2.0.7 on 2018-07-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0018_auto_20180724_1947'),
        ('oddslingers', '0018_merge_20180724_2216'),
    ]

    operations = [
    ]
