# Generated by Django 2.0.7 on 2018-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0020_auto_20180726_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
