# Generated by Django 2.0.8 on 2018-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0021_auto_20180730_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_chat_bubbles',
            field=models.BooleanField(default=True),
        ),
    ]
