# Generated by Django 2.0.8 on 2018-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0022_user_show_chat_bubbles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='light_theme',
            field=models.BooleanField(default=False),
        ),
    ]
