# Generated by Django 2.0.8 on 2018-09-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0023_user_light_theme'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='light_theme',
            field=models.BooleanField(default=True),
        ),
    ]
