# Generated by Django 2.0.8 on 2018-09-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0025_auto_20180926_0300'),
        ('oddslingers', '0024_auto_20180926_0839'),
    ]

    operations = [
    ]
