# Generated by Django 2.0.9 on 2018-12-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0033_user_show_playbyplay'),
        ('oddslingers', '0033_user_stats_and_balance_data_patch_migration'),
    ]

    operations = [
    ]
