# Generated by Django 2.0.8 on 2018-12-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0034_merge_20181207_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='cashtables_level',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userstats',
            name='tournaments_level',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
