# Generated by Django 2.0.8 on 2018-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0037_auto_20181228_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterIndexTogether(
            name='userbalance',
            index_together={('user', 'season')},
        ),
        migrations.AlterIndexTogether(
            name='userstats',
            index_together={('user', 'season')},
        ),
    ]
