# Generated by Django 2.0.8 on 2019-01-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0038_auto_20181228_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='cashtables_level',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='tournaments_level',
        ),
        migrations.AddField(
            model_name='userstats',
            name='games_level',
            field=models.PositiveIntegerField(default=4000),
        ),
    ]
