# Generated by Django 2.0.9 on 2019-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddslingers', '0040_games_level_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muck_after_winning',
            field=models.BooleanField(default=True),
        ),
    ]
